services:
  postgres:
    container_name: postgres_test
    build:
      context: postgres
      dockerfile: ./Dockerfile
    image: "simplon/postgres_test:0.0.1"
    restart: always
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: maria
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5455:5432"

volumes:
  data: